### ISSUE TITLE
Simples XML Error

### ISSUE THREAD

**Issue by NewtonMan** [AlexandrosD/YouTube#2]
Dear my friend,

I hope you'r doing well.

Using your project I am facing problems, using PHP5.4, I am getting an error, see details below, I think this can be a missconfiguration, or an envirement situation that must be workarrounded in your code, exceptions must be trated as well, and I think you can suggest and/or documment the install/configuration better to avoid that.

I will try to solve this, then post the results here.

Keep doing this excelent work man!

Best regards.

**Comment by NewtonMan** [comment]
<?php
require_once 'YouTube/youtube.user.php';

$user = new YouTubeUser( "promoview" );

$userinfo = $user->getInfo();
print_r ( $userinfo );
?>
Results in:
String could not be parsed as XML
Stack Trace

```
CORE/YouTube/youtube.user.php line 114 → SimpleXMLElement->__construct(string)
CORE/YouTube/youtube.user.php line 64 → YouTubeUser->_loadInfo()
APP/View/Elements/youtube/channel.ctp line 6 → YouTubeUser->getInfo()
```

**Comment by NewtonMan** [comment]
Ok, this is a situation where the YouTube user not found.

I see $data in _loadInfo() method as  GDataResourceNotFoundExceptionUser not found.

Maybe you can do a try / catch before try to do a new SimpleXMLElement, you must check if data is XML before do this.

Best regards!

**Comment by AlexandrosD** [comment]
Well it's been a rather long time since I built this library. I am amazed it is still compatible wih

**Comment by AlexandrosD** [comment]
It's been a rather long time since I built this. I have to say I am amazed it still works and any API changes in the meanwhile did not broke it.
